include:
  - template: Security/SAST.gitlab-ci.yml
  - project: 'sci/cicd-templates'
    ref: 'v0.0.2'
    file:
      - '/base/docker-dind.yml'
      - '/jobs/docker-build.yml'
      - '/jobs/push-to-registry.yml'
      - '/rules/version-tag.yml'

stages:
  - .pre
  - test
  - deploy

docker-build:
  extends: .docker-build
  stage: .pre
  variables:
    DOCKERFILE_PATH: "Dockerfile"
    DOCKER_BUILD_CONTEXT: "."
  rules:
    - exists:
      - Dockerfile

semgrep-sast:
  stage: test
  needs:
    - docker-build

test:
  image: $DOCKER_IMAGE_NAME
  stage: test
  tags:
    - autoscale
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  needs:
    - docker-build
  before_script:
    - export KSM_CONFIG=$KSM_CONFIG
    - export SECRET_UID=$SECRET_KEY_UID
    - export S3_ACCESS_KEY=$(ksm secret get -u $SECRET_UID --field "Access Key")
    - export S3_SECRET_KEY=$(ksm secret get -u $SECRET_UID --field "Secret Key")
    - mkdir -p kmer
    - |
      cat > ~/.s3cfg <<EOF
      [default]
      encrypt = False
      access_key = $S3_ACCESS_KEY
      secret_key = $S3_SECRET_KEY
      host_base = $HOST_BASE
      host_bucket = $HOST_BUCKET
      use_https = True
      EOF
    - s3cmd get s3://primer-designer/ci-cd-test-data/kmer-lists/homo_sapiens_11.list kmer/
    - s3cmd get s3://primer-designer/ci-cd-test-data/kmer-lists/homo_sapiens_16.list kmer/
    - ls kmer
  script:
    - python -m unittest discover --start-directory ./tests --top-level-directory .

docker-release:
  extends: .push-to-registry
  stage: deploy
  needs:
    - docker-build
    - test
    - semgrep-sast
  when: on_success
  rules:
    - !reference [.version_tag, rules]
